# Generated by Django 6.0.1 on 2026-02-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_email_verified_at_user_is_email_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("provider", "Provider"),
                    ("admin", "Admin"),
                ],
                default="patient",
                max_length=10,
            ),
        ),
    ]
