# Generated by Django 6.0.1 on 2026-02-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="insurance_document",
            field=models.FileField(
                blank=True, null=True, upload_to="insurance_documents/"
            ),
        ),
    ]
