# Generated by Django 6.0.1 on 2026-02-03 01:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=10)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "clinic_type",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital"),
                            ("clinic", "Clinic"),
                            ("urgent_care", "Urgent Care"),
                            ("free_clinic", "Free Clinic"),
                            ("community_center", "Community Health Center"),
                        ],
                        default="clinic",
                        max_length=20,
                    ),
                ),
                ("accepts_medicaid", models.BooleanField(default=False)),
                ("accepts_medicare", models.BooleanField(default=False)),
                ("sliding_scale", models.BooleanField(default=False)),
                ("free_services", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icon", models.CharField(default="👨\u200d⚕️", max_length=10)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Specialties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                (
                    "license_document",
                    models.FileField(
                        blank=True,
                        help_text="Upload medical license document (PDF, JPG, PNG)",
                        null=True,
                        upload_to="provider_licenses/",
                    ),
                ),
                (
                    "years_experience",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "education",
                    models.TextField(
                        blank=True, help_text="Medical education background"
                    ),
                ),
                (
                    "certifications",
                    models.TextField(
                        blank=True,
                        help_text="Board certifications and additional qualifications",
                    ),
                ),
                (
                    "languages",
                    models.CharField(help_text="Comma-separated list", max_length=200),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("total_reviews", models.IntegerField(default=0)),
                ("accepting_new_patients", models.BooleanField(default=True)),
                ("video_visit_available", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(blank=True, help_text="Reason if rejected"),
                ),
                (
                    "stripe_account_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Connect account ID for payments",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("stripe_onboarding_complete", models.BooleanField(default=False)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        help_text="Platform commission percentage (default 15%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who verified this provider",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-average_rating", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="providers.clinic",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ProviderClinicAffiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "consultation_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="providers.clinic",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "clinic")},
            },
        ),
        migrations.AddField(
            model_name="provider",
            name="clinics",
            field=models.ManyToManyField(
                related_name="providers",
                through="providers.ProviderClinicAffiliation",
                to="providers.clinic",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="specialties",
            field=models.ManyToManyField(
                related_name="providers", to="providers.specialty"
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("visit_date", models.DateField(blank=True, null=True)),
                ("would_recommend", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("provider", "patient")},
            },
        ),
    ]
