# Generated by Django 6.0.1 on 2026-02-02 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("symptoms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="symptomcheck",
            name="ai_metadata",
            field=models.TextField(
                blank=True,
                help_text="JSON object with additional AI analysis data",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="symptomcheck",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="healthtip",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="health_tips",
                to="symptoms.symptomcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="healthtip",
            index=models.Index(
                fields=["-created_at"], name="symptoms_he_created_28d2ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthtip",
            index=models.Index(
                fields=["is_active"], name="symptoms_he_is_acti_c4b70c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="symptomcheck",
            index=models.Index(
                fields=["-created_at"], name="symptoms_sy_created_dfb4d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="symptomcheck",
            index=models.Index(
                fields=["urgency_level"], name="symptoms_sy_urgency_c7d697_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="symptomcheck",
            index=models.Index(
                fields=["patient", "-created_at"], name="symptoms_sy_patient_fa6f61_idx"
            ),
        ),
    ]
